<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>_5_Jahre_Hoelle</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="assets\Achievments.png" />
    <None Remove="assets\ammo_coin.png" />
    <None Remove="assets\ammo_pencil.png" />
    <None Remove="assets\ammo_rubber.png" />
    <None Remove="assets\arrow_back.png" />
    <None Remove="assets\background_vorlaeufig.png" />
    <None Remove="assets\book.png" />
    <None Remove="assets\boss.png" />
    <None Remove="assets\chair_downwards.png" />
    <None Remove="assets\chair_left.png" />
    <None Remove="assets\chair_right.png" />
    <None Remove="assets\chair_upwards.png" />
    <None Remove="assets\desk_dave1.png" />
    <None Remove="assets\desk_dave2.png" />
    <None Remove="assets\desk_erik1.png" />
    <None Remove="assets\desk_erik2.png" />
    <None Remove="assets\desk_vale1.png" />
    <None Remove="assets\desk_vale2.png" />
    <None Remove="assets\Difficulty_Image.png" />
    <None Remove="assets\door_down.png" />
    <None Remove="assets\door_left.png" />
    <None Remove="assets\door_right.png" />
    <None Remove="assets\door_up.png" />
    <None Remove="assets\enemy_back_1.png" />
    <None Remove="assets\enemy_back_2.png" />
    <None Remove="assets\enemy_front_1.png" />
    <None Remove="assets\enemy_front_2.png" />
    <None Remove="assets\enemy_left_1.png" />
    <None Remove="assets\enemy_left_2.png" />
    <None Remove="assets\enemy_right_1.png" />
    <None Remove="assets\enemy_right_2.png" />
    <None Remove="assets\menue.png" />
    <None Remove="assets\Pause %282%29.png" />
    <None Remove="assets\Pause.png" />
    <None Remove="assets\shop_booth.png" />
    <None Remove="assets\front_1.png" />
    <None Remove="assets\front_2.png" />
    <None Remove="assets\links_1.png" />
    <None Remove="assets\links_2.png" />
    <None Remove="assets\menue.png" />
    <None Remove="assets\Pause.png" />
    <None Remove="assets\Player.png" />
    <None Remove="assets\Player_spritesheet.png" />
    <None Remove="assets\Player_up_1.png" />
    <None Remove="assets\Player_up_2.png" />
    <None Remove="assets\rechts_1.png" />
    <None Remove="assets\rechts_2.png" />
    <None Remove="assets\shop_items.png" />
    <None Remove="assets\Stats.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="assets\Achievments.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="assets\Difficulty_Image.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="assets\menue.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="assets\Stats.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Resource Include="assets\ammo_coin.png" />
    <Resource Include="assets\ammo_pencil.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="assets\ammo_rubber.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="assets\arrow_back.png" />
    <Resource Include="assets\book.png" />
    <Resource Include="assets\boss.png" />
    <Resource Include="assets\enemy_back_1.png" />
    <Resource Include="assets\enemy_back_2.png" />
    <Resource Include="assets\enemy_front_1.png" />
    <Resource Include="assets\enemy_front_2.png" />
    <Resource Include="assets\enemy_left_1.png" />
    <Resource Include="assets\enemy_left_2.png" />
    <Resource Include="assets\enemy_right_1.png" />
    <Resource Include="assets\enemy_right_2.png" />
    <Resource Include="assets\front_1.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="assets\front_2.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="assets\links_1.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="assets\links_2.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="assets\background_vorlaeufig.png" />
    <Resource Include="assets\chair_downwards.png" />
    <Resource Include="assets\chair_left.png" />
    <Resource Include="assets\chair_right.png" />
    <Resource Include="assets\chair_upwards.png" />
    <Resource Include="assets\desk_dave1.png" />
    <Resource Include="assets\desk_dave2.png" />
    <Resource Include="assets\desk_erik1.png" />
    <Resource Include="assets\desk_erik2.png" />
    <Resource Include="assets\desk_vale1.png" />
    <Resource Include="assets\desk_vale2.png" />
    <Resource Include="assets\door_down.png" />
    <Resource Include="assets\door_left.png" />
    <Resource Include="assets\door_right.png" />
    <Resource Include="assets\door_up.png" />
    <Resource Include="assets\Pause.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="assets\shop_booth.png" />
    <Resource Include="assets\Player_spritesheet.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="assets\Player_up_1.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="assets\Player_up_2.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="assets\rechts_1.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="assets\rechts_2.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="assets\shop_items.png" />
  </ItemGroup>

  <ItemGroup>
    <Page Update="pages\choose_difficulty.xaml">
      <CopyToOutputDirectory></CopyToOutputDirectory>
    </Page>
    <Page Update="pages\menue_page.xaml">
      <CopyToOutputDirectory></CopyToOutputDirectory>
    </Page>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="questions\" />
  </ItemGroup>

</Project>
