<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>_5_Jahre_Hoelle</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="assets\Achievments.png" />
    <None Remove="assets\Difficulty_Image.png" />
    <None Remove="assets\front_1.png" />
    <None Remove="assets\front_2.png" />
    <None Remove="assets\links_1.png" />
    <None Remove="assets\links_2.png" />
    <None Remove="assets\menue.png" />
    <None Remove="assets\Pause.png" />
    <None Remove="assets\Player.png" />
    <None Remove="assets\Player_spritesheet.png" />
    <None Remove="assets\Player_up_1.png" />
    <None Remove="assets\Player_up_2.png" />
    <None Remove="assets\rechts_1.png" />
    <None Remove="assets\rechts_2.png" />
    <None Remove="assets\Stats.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="assets\Achievments.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="assets\Difficulty_Image.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="assets\menue.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="assets\Stats.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Resource Include="assets\front_1.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="assets\front_2.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="assets\links_1.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="assets\links_2.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="assets\Pause.png" />
    <Resource Include="assets\Player_spritesheet.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="assets\Player_up_1.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="assets\Player_up_2.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="assets\rechts_1.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="assets\rechts_2.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <Page Update="pages\choose_difficulty.xaml">
      <CopyToOutputDirectory></CopyToOutputDirectory>
    </Page>
    <Page Update="pages\menue_page.xaml">
      <CopyToOutputDirectory></CopyToOutputDirectory>
    </Page>
  </ItemGroup>

</Project>
